// src/views/Home.vue
<template>
  <div class="home">
    <div>
      <p>
        Enter a <b>Philly address</b> or <b>landlord's name</b> to find out who
        owns what in Philly what else they might own in the city, and any
        complaints, violations, real estate transactions, and active rental
        licenses associated with their properties.
      </p>
      <p>
        <b>Can't find the address?</b> Click
        <a href="https://atlas.phila.gov"> here</a> or
        <a href="https://phillypropertylookup.herokuapp.com">here</a> to see how
        the city formats addresses and owner names. We try our best to search in a similar way, but sometimes the city renames addresses in ways we can't detect.
      </p>
    </div>
    <sui-divider hidden />
    <SearchBar />
    <sui-divider hidden />
    <ExampleOwners />
  </div>
</template>

<script>
// @ is an alias to /src

import SearchBar from "@/components/SearchBar";
import ExampleOwners from "@/components/ExampleOwners";

export default {
  name: "Home",
  components: {
    SearchBar,
    ExampleOwners
  }
};
</script>
<style>
.home {
  padding: 50px;
}
</style>

// solid/src/routes/Home.tsx
import {Component} from "solid-js";
import AddressSearch from "../components/AddressSearch";

const Home: Component = () => {
   return (<main class="flex flex-col items-center h-screen pt-36 p-4">
        <h1 class="text-4xl text-bold text-emerald-800">Who Owns Philly?</h1>
        <p class="text-center"> Find out who owns what in Philly, what else
            they might own in the city, and information about their properties.</p>

        <div class="py-8 flex w-full lg:w-1/2 flex-col items-center">
            <AddressSearch/>
            <div class="text-center">
                Enter a <b>Philly address</b>, <b>landlord's name</b>, or <b>property manager</b>.
            </div>
            <div class="w-3/4 flex flex-col items-center gap-4">
                <p class="text-center">
                    <b>Is the address not showing up?</b> Search for the address on
                    <a href="https://atlas.phila.gov">atlas.phila.gov</a> to see how the
                    City formats addresses and owner names. We try our best to match
                    addresses to the City’s format, but sometimes the City formats addresses
                    in ways we can't detect.
                </p>
            </div>
        </div>
    </main>)
}


export default Home
