// web/src/components/properties/PropertyOwner.tsx
import {Component, createEffect, createSignal, Show} from "solid-js";
import {
    getOwnerPageInfoByMailingAddress, getOwnerPageInfoByName,
} from "../../services/apiFetcher";
import {CurrencyFormatter} from "../../services/utility.helper";
import PropertyOwnerMap from "./components/PropertyOwnerMap";

const PropertyOwner: Component = (props) => {

    const [mailingAddressInfo, setMailingAddressInfo] = createSignal({})
   // const [ownerInfo, setOwnerInfo] = createSignal({})

    const [violationDate] = createSignal(new Date(2006, 6, 1))
    const [properties, setProperties] = createSignal([])
    const [propertySummary, setPropertySummary ] = createSignal(0)
    createEffect(async () => {
        const [mailingResults, ownerResults] = await Promise.all([
            getOwnerPageInfoByMailingAddress(props.id, violationDate()),
            getOwnerPageInfoByName(props.id, violationDate())])

        const mailingInfo = {
                    mailingAddress: mailingResults["metadata"]["mailing_address"],
                    mailingAddressBasedNames: mailingResults["results"]["alias_names"],
                    mailingAddressBasedMailingCareOfNames:  mailingResults["results"]["mailing_care_of_names"],
                    mailingAddressBasedPropertyTimelineData: mailingResults["results"]["timeline"],
                    mailingAddressBasedViolations: mailingResults["results"]["violations"],
                    mailingAddressBasedComplaints: mailingResults["results"]["complaints"],
                    mailingAddressBasedOwnerPropertyCountsByName: mailingResults["display_inputs"]["owner_property_counts_by_name"],
                }
        setMailingAddressInfo(mailingInfo)
        const ownerInfo = {
                ownerBasedPropertyTimelineData: ownerResults["results"]["timeline"],
                ownerBasedViolations: ownerResults["results"]["violations"],
                ownerBasedComplaints: ownerResults["results"]["complaints"],
                ownerBasedNames: ownerResults["results"]["alias_names"],
                ownerBasedOwnerPropertyCountsByName: ownerResults["display_inputs"]["owner_property_counts_by_name"],
            }

        const allProperties = ownerInfo.ownerBasedPropertyTimelineData.concat(mailingInfo.mailingAddressBasedPropertyTimelineData)
        const propertySummary = { value: 0, complaints: 0, open: 0, closed: 0 }
        let allUniqueCurrentProperties = []
        let allUniquePropertyParcelNumbers = [];
        allProperties.forEach((property) => {
            if (
                !allUniquePropertyParcelNumbers.includes(
                    property.opa_account_num
                )
            ) {
                allUniquePropertyParcelNumbers.push(property.opa_account_num);
                propertySummary.open += property.n_violations_open;
                propertySummary.closed += property.n_violations_closed;
                propertySummary.complaints += property.n_complaints;
                propertySummary.value += property.market_value;
                if (property.current_owner === true) {
                    allUniqueCurrentProperties.push(property);
                }
            }
        })
        setProperties(allUniqueCurrentProperties)
        setPropertySummary(propertySummary)
    })

    return (
        <section class="flex flex-col w-full">
        <div class="flex flex-col flex-col-reverse w-full lg:flex-row gap-4">
            <div class="w-full lg:w-1/2 h-[50vh]">
                <PropertyOwnerMap properties={properties()} />
            </div>
            <div class="w-full lg:w-1/2">
                <div>
                    <div>Mailing Address</div>
                    <span class="text-sm lg:text-xl"> {mailingAddressInfo().mailingAddress}</span>
                </div>
                <Show when={mailingAddressInfo().mailingAddressBasedMailingCareOfNames}>
                    <div class="text-sm lg:text-base">
                        <div class="border-t pt-2">Mailing Care Of</div>
                        <span> {mailingAddressInfo().mailingAddressBasedMailingCareOfNames.join(", ")}</span>
                    </div>
                </Show>
                <div class="flex flex-col w-full border border-black divide-emerald-800">
                    <div class="bg-neutral-300 text-center">Properties currently associated with owner</div>
                    <div class="flex w-full">
                        <div class="w-1/2 bg-neutral-300 px-2 text-center">Properties</div>
                        <div class="w-1/2 bg-neutral-300 px-2 text-center">Total Value</div>
                    </div>
                    <div class="border-t border-black divide-x divide-black flex">
                        <div class="w-1/2 text-center p-2 text-xl">{ properties().length } </div>
                        <div class="w-1/2 text-center p-2 text-xl">{ CurrencyFormatter.USDollar.format(propertySummary().value) }</div>
                    </div>
                </div>
                <div class="mt-4 flex w-full border border-black">
                    <div class="divide-y divide-black">
                        <div class="bg-neutral-300 px-2 text-center">Open Violations</div>
                        <div class="text-2xl text-center pt-4"> { propertySummary().open }</div>
                    </div>
                    <div class="grow border-l border-black">
                        <div class="bg-neutral-300 text-center">Since {new Date(violationDate()).toLocaleString('en-us', { year:"numeric", month:"short", day:"numeric"})}</div>
                        <div class="flex w-full">
                            <div class="w-1/2 bg-neutral-300 px-2 text-center">Closed Violations</div>
                            <div class="w-1/2 bg-neutral-300 px-2 text-center">Complaints</div>
                        </div>
                        <div class="border-t border-black divide-x divide-black flex">
                            <div class="w-1/2 text-center p-2 text-xl">{ propertySummary().closed } </div>
                            <div class="w-1/2 text-center p-2 text-xl">{ propertySummary().complaints }</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="max-w-6xl">
            <table class="w-6xl">
                <thead>
                <tr>
                    <th>color</th>
                    <th>current_owner</th>
                    <th>document_id</th>
                    <th>lat</th>
                    <th>likely_owner</th>
                    <th>lng</th>
                    <th>location</th>
                    <th>location_unit</th>
                    <th>mailing_address_1</th>
                    <th>mailing_address_2</th>
                    <th>mailing_care_of</th>
                    <th>mailing_city_state</th>
                    <th>mailing_street</th>
                    <th>mailing_zip</th>
                    <th>market_value</th>
                    <th>complaints</th>
                    <th>violations</th>
                    <th>violations_closed</th>
                    <th>violations_open</th>
                    <th>opa_account_num</th>
                    <th>opa_address</th>
                    <th>opa_address_unit</th>
                    <th>property_count</th>
                    <th>sold_to</th>
                    <th>source</th>
                    <th>start_dt</th>
                    <th>unit</th>
                </tr>
                </thead>

            </table>
        </div>
        </section>
 )
}

export default PropertyOwner

// src/components/properties/PropertyOwner.vue
<script setup lang="ts">
  import PropertyOwnerMap from "./PropertyOwnerMap.vue";
  import {getOwnerPageInfoByMailingAddress, getOwnerPageInfoByName} from "../../services/apiFetcher";
  import {computed, onMounted, reactive, ref, watch} from "vue";
  import {CurrencyFormatter} from "../../services/utility.helper";
  import LoadingMap from "../ui/LoadingMap.vue";
  import {IconLoader5Line} from "@iconify-prerendered/vue-ri";

  const mailingAddressInfo = ref<any>({})
  const ownerInfo = ref({})
  const violationDate = ref<any>(new Date(2006, 6, 1))
  const properties = ref<any>(new Array<any>())
  const propertySummary = reactive({ amount: 0, complaints: 0, open: 0, closed: 0 })

  const props = defineProps({
    id: { type: String, required: true }
  })

  const pageState = reactive({
    isLoading: true,
    loadingPercent: 0,
    activeListTab: 'owner',
    activeListType: 'timeline'
  })



  const filteredList = computed(() => {
    const list = pageState.activeListTab === "owner" ? ownerInfo.value : mailingAddressInfo.value
    return list[pageState.activeListType]
  })

  const getPropertyLink = (id: number) => {
    return `/properties/${id}/summary`
  }

  const loadData = async (propertyId: string) => {
    pageState.isLoading = true

    // TODO add date parameter
    const [mailingResults, ownerResults] = await Promise.all([
      getOwnerPageInfoByMailingAddress(propertyId),
      getOwnerPageInfoByName(propertyId)])

    mailingAddressInfo.value = {
      mailingAddress: mailingResults["metadata"]["mailing_address"],
      names: mailingResults["results"]["alias_names"],
      mailingCareOfNames:  mailingResults["results"]["mailing_care_of_names"],
      timeline: mailingResults["results"]["timeline"],
      violations: mailingResults["results"]["violations"],
      complaints: mailingResults["results"]["complaints"],
      ownerPropertyCountsByName: mailingResults["display_inputs"]["owner_property_counts_by_name"],
    }

    ownerInfo.value = {
      timeline: ownerResults["results"]["timeline"],
      violations: ownerResults["results"]["violations"],
      complaints: ownerResults["results"]["complaints"],
      names: ownerResults["results"]["alias_names"],
      ownerPropertyCountsByName: ownerResults["display_inputs"]["owner_property_counts_by_name"],
    }

    const allProperties = ownerInfo.value.timeline
        .concat(mailingAddressInfo.value.timeline)

    let allUniqueCurrentProperties = []
    let allUniquePropertyParcelNumbers = [];
    allProperties.forEach((property) => {
      if (
          !allUniquePropertyParcelNumbers.includes(
              property.opa_account_num
          )
      ) {
        allUniquePropertyParcelNumbers.push(property.opa_account_num);
        propertySummary.open += property.n_violations_open;
        propertySummary.closed += property.n_violations_closed;
        propertySummary.complaints += property.n_complaints;
        propertySummary.amount += property.market_value;
        if (property.current_owner === true) {
          allUniqueCurrentProperties.push(property);
        }
      }
    })
    properties.value = allUniqueCurrentProperties
    pageState.isLoading = false

  }
  onMounted(async () => {
    // TODO return these first but run in parallel. RXJS?
    await loadData(props.id)
  })

  watch(() => props.id, async (value) => {
    await loadData(value)
  })

</script>

<template>
  <section class="flex flex-col w-full">
    <div v-if="pageState.isLoading" class="bg-gray-200 p-4 rounded-sm flex justify-between mb-4">
      <div class="w-full text-center">
        <span>Loading could take up to 30 seconds</span>
      </div>
      <icon-loader5-line class="animate-spin text-2xl text-gray-500"/>
    </div>
    <div class="flex flex-col flex-col-reverse w-full lg:flex-row gap-4">
      <div class="w-full lg:w-1/2 h-[80vh]">
        <LoadingMap v-if="pageState.isLoading" />
        <PropertyOwnerMap :properties=properties v-if="!pageState.isLoading" />
      </div>
      <div class="w-full flex flex-col lg:w-1/2">
        <div>
          <div>
            <div class="font-bold">Mailing Address</div>
            <span class="text-sm lg:text-xl"> {{mailingAddressInfo.mailingAddress}}</span>
          </div>
          <div v-if="mailingAddressInfo.mailingAddressBasedMailingCareOfNames" class="text-sm lg:text-base">
            <div class="border-t pt-2">Mailing Care Of</div>
            <span> {{mailingAddressInfo.mailingAddressBasedMailingCareOfNames.join(", ")}}</span>
          </div>
          <div class="flex flex-col w-full border border-black divide-emerald-800">
            <div class="bg-neutral-300 text-center">Properties currently associated with owner</div>
            <div class="flex w-full">
              <div class="w-1/2 bg-neutral-300 px-2 text-center">Properties</div>
              <div class="w-1/2 bg-neutral-300 px-2 text-center">Total Value</div>
            </div>
            <div class="border-t border-black divide-x divide-black flex">
              <div class="w-1/2 text-center p-2 text-xl">{{ properties.length }} </div>
              <div class="w-1/2 text-center p-2 text-xl">{{ CurrencyFormatter.USDollar.format(propertySummary.amount) }}</div>
            </div>
          </div>
          <div class="mt-4 flex w-full border border-black">
            <div class="divide-y divide-black">
              <div class="bg-neutral-300 px-2 text-center">Open Violations</div>
              <div class="text-2xl text-center pt-4"> {{ propertySummary.open }}</div>
            </div>
            <div class="grow border-l border-black">
              <div class="bg-neutral-300 text-center">Since {{new Date(violationDate).toLocaleString('en-us', { year:"numeric", month:"short", day:"numeric"})}}</div>
              <div class="flex w-full">
                <div class="w-1/2 bg-neutral-300 px-2 text-center">Closed Violations</div>
                <div class="w-1/2 bg-neutral-300 px-2 text-center">Complaints</div>
              </div>
              <div class="border-t border-black divide-x divide-black flex">
                <div class="w-1/2 text-center p-2 text-xl">{{ propertySummary.closed }} </div>
                <div class="w-1/2 text-center p-2 text-xl">{{ propertySummary.complaints }}</div>
              </div>
            </div>
          </div>
        </div>
        <div class="flex flex-col grow">
          <h3 class="mt-4 flex w-full justify-between font-bold mb-2">Property Violations<span class="font-normal">Record Count: {{filteredList?.length}}</span></h3>
          <div class="w-full flex">
            <button class="nav-button w-full" :class="{active: pageState.activeListTab === 'owner'}" @click="pageState.activeListTab = 'owner'">Owner</button>
            <button class="nav-button w-full" :class="{active: pageState.activeListTab === 'mailing'}" @click="pageState.activeListTab = 'mailing'">Mailing Address</button>
          </div>
          <div class="mt-1 w-full flex">
            <button class="nav-button w-full" :class="{active: pageState.activeListType === 'timeline'}" @click="pageState.activeListType = 'timeline'">Properties</button>
            <button class="nav-button w-full" :class="{active: pageState.activeListType === 'violations'}" @click="pageState.activeListType = 'violations'">Violations</button>
            <button class="nav-button w-full" :class="{active: pageState.activeListType === 'complaints'}" @click="pageState.activeListType = 'complaints'">311 Complaints</button>
          </div>
          <!-- TODO
          Show different columns for each type
          properties:  likely_owner, location, unit, n_days_owned, n_complaints, n_violations, n_violations_open, opa_account_num
          violations:  likely_owner, location, unit, opa_account_num, violationcodetitle, violationdate, violationnumber, violationresolutioncode, violationstatus
          complaints: likely_owner, location, unit, complaint_date, complaint_number, complaint (empty right now), opa_account_num
          -->
          <div class="overflow-auto grow h-[50vh]]">
            <div class="flex items-center mt-2 border pr-2" v-if="pageState.activeListTab === 'mailing'">
              <span class="bg-gray-100 px-2 py-1 mr-2">NAMES</span> {{mailingAddressInfo.names.join("; ")}}
            </div>
            <table class="w-full text-xs sm:text-sm" v-if="pageState.activeListType === 'timeline'">
              <thead>
                <tr>
                  <th colspan="4"></th>
                  <th colspan="2" class="text-center">Violations</th>
                  <th></th>
                </tr>
                <tr>
                  <th v-if="pageState.activeListTab === 'owner'">Owner</th>
                  <th>Location</th>
                  <th>Days <span class="hidden sm:block">Owned</span></th>
                  <th>Complaints</th>
                  <th>Total</th>
                  <th>Open</th>
                  <th>OPA <span class="hidden sm:block">Number</span></th>
                </tr>
              </thead>
              <tbody>
                <tr class="hover:bg-gray-100" v-for="(item, index) in filteredList" v-bind:key="index">
                  <td v-if="pageState.activeListTab === 'owner'">{{item.likely_owner}}</td>
                  <td class="whitespace-nowrap" >{{item.location}} {{ item?.unit}}</td>
                  <td class="text-right">{{item.n_days_owned}}</td>
                  <td class="text-right">{{item.n_complaints}}</td>
                  <td class="text-right">{{item.n_violations}}</td>
                  <td class="text-right">{{item.n_violations_open}}</td>
                  <td class="text-right"><a :href="getPropertyLink(item.opa_account_num)">{{item.opa_account_num}}</a> </td>
                </tr>
              </tbody>
            </table>
            <table class="w-full text-xs sm:text-sm"  v-if="pageState.activeListType === 'violations'">
              <thead>
                <tr>
                  <th v-if="pageState.activeListTab === 'owner'">Owner</th>
                  <th>Location</th>
                  <th>Title</th>
                  <th>Date</th>
                  <th>Number</th>
                  <th>Resolution</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody class="text-xs whitespace-nowrap">
                <tr class="hover:bg-gray-100" v-for="(item, index) in filteredList" v-bind:key="index">
                  <td v-if="pageState.activeListTab === 'owner'">{{item.likely_owner}}</td>
                  <td>{{item.location}} {{ item?.unit}}</td>
                  <td>{{item.violationcodetitle}}</td>
                  <td>{{item.violationdate}}</td>
                  <td>{{item.violationnumber}}</td>
                  <td>{{item.violationstatus}}</td>
                  <td>{{item.violationresolutioncode}}</td>
                </tr>
              </tbody>
            </table>
            <table  class="w-full text-xs sm:text-sm" v-if="pageState.activeListType === 'complaints'">
              <thead>
              <tr>
                <th v-if="pageState.activeListTab === 'owner'">Owner</th>
                <th>Location</th>
                <th>Date</th>
                <th>Number</th>
                <th>Complaint</th>
              </tr>
              </thead>
              <tbody class="whitespace-nowrap">
              <tr class="hover:bg-gray-100"  v-for="(item, index) in filteredList" v-bind:key="index">
                <td v-if="pageState.activeListTab === 'owner'">{{item.likely_owner}}</td>
                <td>{{item.location}} {{ item?.unit}}</td>
                <td>{{item.complaintdate}}</td>
                <td>{{item.complaintnumber}}</td>
                <td></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
table tbody tr td {
  @apply pr-1
}
.nav-button {
  @apply px-6 py-2 rounded-sm bg-gray-100 border border-white text-black;
}

.nav-button:hover {
  @apply bg-neutral-400 text-white
}

.active  {
  @apply bg-neutral-500 text-white
}
</style>
