// src/components/AddressSearch.vue
<script setup lang="ts">
import {ref} from "vue";
import axios from "axios";

const domain = import.meta.env.PUBLIC_API_DOMAIN

const filteredItems = ref([]);
const filterItems = async (event) => {
  const inputValue = event.target.value
  if (event.target.value && inputValue.length > 3) {
    const endpoint = `${domain}api/v1/autocomplete?startswith_str=${inputValue.toLowerCase()}`
    const result = await axios.get(endpoint)
    filteredItems.value = result.data.results
  }
}
</script>

<template>
  <section class="w-full">
    <input class="py-4 px-8 w-full rounded-full border text-xl hover:shadow-md focus:shadow-md focus:outline-none"
           type="text"
           @input="filterItems"
           placeholder="Search address owner..."/>
    <div v-if="filteredItems.length > 0" >
      <ul class="relative mt-1 w-full border divide-y shadow-md rounded-sm">
        <li  class="p-2 hover:text-emerald-800 hover:cursor-pointer"  v-for="item in filteredItems" v-bind:key="item.computed_location">
          <a :href="`/properties/${item['opa_account_num']}/summary`">{{item.computed_location}}</a>
        </li>
      </ul>
    </div>
  </section>
</template>

<style scoped>

</style>

// web/src/components/AddressSearch.tsx
import {Component, createSignal, For, Show} from "solid-js";
import axios from "axios";



const domain = "http://localhost:8081/"

const AddressSearch: Component = () => {
    // const navigate = useNavigate();
    const [filteredItems, setFilteredItems] = createSignal([]);
    const filterItems = async (event) => {
        const inputValue = event.target.value
        if (event.target.value && inputValue.length > 3) {
            const endpoint = `${domain}api/v1/autocomplete?startswith_str=${inputValue.toLowerCase()}`
            const result = await axios.get(endpoint)
            setFilteredItems(result.data.results)
        }
    }

    const selectItem = (item) => {

        // let propertyId = item["opa_account_num"];
        // navigate(`/properties/${propertyId}`, { replace: true })
    }
    return (
        <>
            <input class="py-4 px-8 w-full rounded-full border text-xl hover:shadow-md focus:shadow-md focus:outline-none"
                   type="text"
                   onInput={filterItems}
                   placeholder="Search address or owner..."/>
        <Show when={filteredItems().length > 0} >
            <ul class="relative mt-2 w-full border divide-y shadow-md rounded-lg">
                <For each={filteredItems()}>
                    {(item) =>
                        <li class="p-2 hover:bg-emerald-200 hover:cursor-pointer" onclick={[selectItem, item]} >
                            {item.computed_location}
                        </li>
                    }
                </For>
            </ul>
        </Show>
        </>)
}

export default AddressSearch
